// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhddghvbrssbtkosrsjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoZGRnaHZicnNzYnRrb3Nyc2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTQ1NzUsImV4cCI6MjA3MjI5MDU3NX0.XYCw5NOmn3CoJ9TbLWuxSdMQqST4UveHkkOI1oM4c54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});